CREATE DATABASE customers;
use customers;
show tables;
select * from customer_data limit 20;


-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,sum(purchase_amount) as revenue
FROM customer_data
Group by gender;
-- Revenue by male customers - $157890
-- Revenue by Female customers - $ 75191

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id , purchase_amount
FROM customer_data 
where discount_applied = 'Yes'
AND purchase_amount > (select  AVG(purchase_amount) from customer_data);


-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased, round(avg(review_rating),2)
from customer_data
Group by item_purchased
order by avg(review_rating) DESC limit 5;

-- Gloves	3.86
-- Sandals	3.84
-- Boots	3.82
-- Hat	3.8
-- Skirt	3.78

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select shipping_type , avg(purchase_amount) 
from customer_data
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Express	60.4752
-- Standard	58.4602

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue 
-- between subscribers and non-subscribers.

select subscription_status,
 COUNT(customer_id) AS total_customers,  avg(purchase_amount) ,
 sum(purchase_amount) as total_revenue
 from customer_data
 group by subscription_status
 order by total_revenue;

-- Yes	1053	59.4919	62645
-- No	2847	59.8651	170436

--  Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Hat	50.00
-- Sneakers	49.66
-- Coat	49.07
-- Sweater	48.17
-- Pants	47.37

-- Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type as
 (select customer_id , previous_purchases,
CASE
when previous_purchases=1 then 'New'
when  previous_purchases between 2 AND 10  then 'Returning'
else 'Loyal'
END as customer_segment 
from customer_data)

select count(*) as count, customer_segment 
from customer_type
group by customer_segment;

-- 3116	Loyal
-- 701	Returning
-- 83	New

-- Q8. What are the top 3 most purchased products within each category? 

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_data
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;


 
-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer_data
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Yes	958
-- No	2518


-- Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer_data
GROUP BY age_group
ORDER BY total_revenue desc;

-- Young Adult	62143
-- Midde-Aged	59197
-- Adult	55978
-- Senior	55763